mac_address: F2:7D:17:78:73:80
stand_height: 1115
sit_height: 730
height_tolerance: 1.5
scan_timeout: 10
connection_timeout: 20
movement_timeout: 30
adapter_name: hci0
server_address": "127.0.0.1"
server_port: 9123
